# Generated by Django 4.2.7 on 2025-12-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usuario_options_usuario_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='MiNota IPST', max_length=100)),
                ('logo_url', models.URLField(blank=True, help_text='URL del logo de la institución', null=True)),
                ('color_primario', models.CharField(default='#1976d2', help_text='Código Hex (ej: #1976d2)', max_length=7)),
                ('color_secundario', models.CharField(default='#dc004e', help_text='Código Hex', max_length=7)),
                ('banner_activo', models.BooleanField(default=False)),
                ('banner_mensaje', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_tipo', models.CharField(choices=[('info', 'Información'), ('warning', 'Alerta'), ('error', 'Error')], default='info', max_length=20)),
            ],
            options={
                'verbose_name': 'Configuración Institución',
                'verbose_name_plural': 'Configuración Institución',
            },
        ),
    ]
