# Generated by Django 5.2 on 2025-05-22 03:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Asignatura')),
                ('subject_type', models.CharField(choices=[('carrera', 'Asignatura de Carrera (5.5)'), ('complementaria', 'Asignatura Complementaria (5.3)')], max_length=15, verbose_name='Tipo de Asignatura')),
                ('class_type', models.CharField(choices=[('teoria', 'Teoría (75% asistencia)'), ('laboratorio', 'Laboratorio (90% asistencia)'), ('mixto', 'Mixto (Teoría + Laboratorio)')], default='teoria', max_length=15, verbose_name='Tipo de Clase')),
                ('total_evaluations', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Cantidad Total de Evaluaciones')),
                ('total_theory_classes', models.PositiveIntegerField(default=0, verbose_name='Total de Clases Teóricas')),
                ('total_lab_classes', models.PositiveIntegerField(default=0, verbose_name='Total de Clases de Laboratorio')),
                ('has_attendance_reduction', models.BooleanField(default=False, verbose_name='Tiene Rebaja de Asistencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GradeCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_data', models.JSONField(verbose_name='Datos del Cálculo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cálculo')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='grades.subject', verbose_name='Asignatura')),
            ],
            options={
                'verbose_name': 'Cálculo de Notas',
                'verbose_name_plural': 'Cálculos de Notas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Evaluación')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100.0)], verbose_name='Porcentaje (%)')),
                ('grade', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(7.0)], verbose_name='Nota Obtenida')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Evaluación Completada')),
                ('date_completed', models.DateField(blank=True, null=True, verbose_name='Fecha de Realización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='grades.subject', verbose_name='Asignatura')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory_absences', models.PositiveIntegerField(default=0, verbose_name='Inasistencias Teoría')),
                ('lab_absences', models.PositiveIntegerField(default=0, verbose_name='Inasistencias Laboratorio')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='grades.subject', verbose_name='Asignatura')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
