# Generated by Django 4.2.7 on 2025-06-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='class_type',
            field=models.CharField(choices=[('teoria', 'Teoría (75% asistencia)'), ('laboratorio', 'Laboratorio (90% asistencia)')], default='teoria', max_length=15, verbose_name='Tipo de Clase'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('carrera', 'Asignatura de Carrera (5.3)'), ('complementaria', 'Asignatura Complementaria (5.5)')], max_length=15, verbose_name='Tipo de Asignatura'),
        ),
    ]
